name: flutter_base
description: "A professional Flutter starter template."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2

  google_fonts: ^6.1.0
  modal_bottom_sheet: ^3.0.0
  
  # State & Storage
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true # Check this for l10n generation

  # assets:
  #   - assets/images/
